"""Type stubs for rest_framework_simplejwt.tokens."""

from __future__ import annotations

from typing import Any

class Token:
    """JWT Token base class."""

    def __init__(self, token: str | bytes | None = None, verify: bool = True) -> None: ...
    def __str__(self) -> str: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    @classmethod
    def for_user(cls, user: Any) -> Token: ...
    @property
    def access_token(self) -> AccessToken: ...
    def blacklist(self) -> None: ...

class AccessToken(Token): ...

class RefreshToken(Token):
    """JWT Refresh Token."""

    def __init__(self, token: str | bytes | None = None, verify: bool = True) -> None: ...
    @classmethod
    def for_user(cls, user: Any) -> RefreshToken: ...
    @property
    def access_token(self) -> AccessToken: ...
