name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - "apps/client/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          cd apps/client
          npm install

      - name: Build Nuxt
        run: |
          cd apps/client
          npm run build

      - name: Deploy
        run: echo "Déploiement en cours..."
