# Generated by Django 5.2.1 on 2026-03-02 23:19

import core.projects.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Statut de projet',
                'verbose_name_plural': 'Statuts de projets',
                'db_table': 'project_status',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categorie de projet',
                'verbose_name_plural': 'Categories de projets',
                'db_table': 'project_categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='project_cat_slug_8c8c80_idx')],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField()),
                ('long_description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.projects.models.project_image_upload_to)),
                ('technologies', models.JSONField(default=list)),
                ('features', models.JSONField(blank=True, default=list)),
                ('links', models.JSONField(blank=True, default=dict, help_text="Format JSON: {'demo': 'url', 'github': 'url', 'documentation': 'url'}")),
                ('date', models.DateField(default=datetime.date.today)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.projectcategory')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.projectstatus')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'db_table': 'projects',
                'ordering': ['-date', 'title'],
                'indexes': [models.Index(fields=['slug'], name='projects_slug_25ccba_idx'), models.Index(fields=['date'], name='projects_date_e1b204_idx'), models.Index(fields=['category'], name='projects_categor_c363bc_idx'), models.Index(fields=['status'], name='projects_status__418086_idx'), models.Index(fields=['-view_count'], name='projects_view_co_a80343_idx'), models.Index(fields=['category', '-date'], name='projects_categor_b96643_idx'), models.Index(fields=['status', '-date'], name='projects_status__33dec7_idx')],
            },
        ),
    ]
