# Generated by Django 5.2.12 on 2026-03-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="meta_description",
            field=models.CharField(
                blank=True, help_text="Meta description (max 160 car.). Utilise la description si vide.", max_length=160
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="seo_title",
            field=models.CharField(
                blank=True, help_text="Titre SEO (max 70 car.). Utilise le titre si vide.", max_length=70
            ),
        ),
    ]
