# Generated by Django 5.2.1 on 2026-03-02 23:19

import core.stacks.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StackCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Categorie de stack',
                'verbose_name_plural': 'Categories de stacks',
                'db_table': 'stack_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField()),
                ('logo', models.FileField(blank=True, help_text='Logo (PNG, JPG, GIF, WebP ou SVG)', null=True, upload_to=core.stacks.models.stack_logo_upload_to, validators=[core.stacks.models.validate_logo_file])),
                ('tags', models.JSONField(default=list)),
                ('started_date', models.DateField(blank=True, help_text="Date de début d'utilisation de cette technologie", null=True)),
                ('level', models.DecimalField(decimal_places=1, default=Decimal('0.5'), help_text='Niveau de maitrise (0.5-5.0)', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('5.0'))])),
                ('website', models.URLField(blank=True, null=True)),
                ('website_label', models.CharField(blank=True, max_length=50, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('github_label', models.CharField(blank=True, max_length=50, null=True)),
                ('first_release', models.CharField(blank=True, max_length=50)),
                ('license', models.CharField(blank=True, max_length=50)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stacks', to='stacks.stackcategory')),
            ],
            options={
                'verbose_name': 'Stack technique',
                'verbose_name_plural': 'Stacks techniques',
                'db_table': 'stacks',
                'ordering': ['-level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StackRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('alternative', 'Alternative'), ('complementary', 'Complementaire'), ('dependency', 'Dependance'), ('similarTo', 'Similaire')], default='similarTo', max_length=20)),
                ('from_stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='stacks.stack')),
                ('to_stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_from', to='stacks.stack')),
            ],
            options={
                'verbose_name': 'Relation entre stacks',
                'verbose_name_plural': 'Relations entre stacks',
                'db_table': 'stack_relationships',
            },
        ),
        migrations.AddField(
            model_name='stack',
            name='related_stacks_m2m',
            field=models.ManyToManyField(related_name='related_to', through='stacks.StackRelationship', to='stacks.stack'),
        ),
        migrations.CreateModel(
            name='StackResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('type', models.CharField(choices=[('documentation', 'Documentation'), ('tutorial', 'Tutoriel'), ('article', 'Article'), ('video', 'Video'), ('other', 'Autre')], default='documentation', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='stacks.stack')),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
                'db_table': 'stack_resources',
                'ordering': ['-is_featured', 'title'],
            },
        ),
        migrations.AddIndex(
            model_name='stackrelationship',
            index=models.Index(fields=['from_stack', 'relationship_type'], name='stack_relat_from_st_41b70c_idx'),
        ),
        migrations.AddConstraint(
            model_name='stackrelationship',
            constraint=models.UniqueConstraint(fields=('from_stack', 'to_stack'), name='unique_stack_relationship'),
        ),
        migrations.AddIndex(
            model_name='stack',
            index=models.Index(fields=['slug'], name='stacks_slug_08c7f8_idx'),
        ),
        migrations.AddIndex(
            model_name='stack',
            index=models.Index(fields=['level'], name='stacks_level_00765f_idx'),
        ),
        migrations.AddIndex(
            model_name='stack',
            index=models.Index(fields=['category'], name='stacks_categor_7d04ec_idx'),
        ),
        migrations.AddIndex(
            model_name='stackresource',
            index=models.Index(fields=['stack', 'type'], name='stack_resou_stack_i_52c7a0_idx'),
        ),
    ]
