# Generated by Django 5.2.1 on 2026-03-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stackrelationship',
            constraint=models.CheckConstraint(condition=models.Q(('from_stack', models.F('to_stack')), _negated=True), name='prevent_self_relationship'),
        ),
    ]
