# Generated by Django 5.2.1 on 2026-03-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stacks", "0002_stackrelationship_prevent_self_relationship"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="stackrelationship",
            index=models.Index(fields=["to_stack"], name="stack_relat_to_stac_d89678_idx"),
        ),
    ]
