# Generated by Django 5.2.1 on 2026-03-02 23:26

import core.transfer.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=50)),
                ('format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV'), ('xlsx', 'Excel')], default='json', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Termine'), ('failed', 'Echoue')], default='pending', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to=core.transfer.models.export_file_upload_to)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('records_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Job d'export",
                'verbose_name_plural': "Jobs d'export",
                'db_table': 'data_transfer_export_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='data_transf_status_7c13ec_idx'), models.Index(fields=['user'], name='data_transf_user_id_3d476b_idx'), models.Index(fields=['module'], name='data_transf_module_03b411_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('validating', 'Validation'), ('processing', 'En cours'), ('completed', 'Termine'), ('failed', 'Echoue'), ('partially_completed', 'Partiellement termine')], default='pending', max_length=30)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_format', models.CharField(max_length=10)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('processed_records', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Job d'import",
                'verbose_name_plural': "Jobs d'import",
                'db_table': 'data_transfer_import_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='data_transf_status_ef2fb5_idx'), models.Index(fields=['user'], name='data_transf_user_id_ab8d02_idx'), models.Index(fields=['module'], name='data_transf_module_43e208_idx')],
            },
        ),
    ]
