[pytest]
DJANGO_SETTINGS_MODULE = config.settings_test
python_files = tests.py test_*.py *_tests.py
addopts = -v --tb=short --ds=config.settings_test --cov=core --cov=utils --cov-report=term-missing --cov-fail-under=30
testpaths = tests
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore:Accessing the database during app initialization is discouraged:RuntimeWarning
