# Generated by Django 5.2.1 on 2026-03-02 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom descriptif du webhook', max_length=100, verbose_name='Nom')),
                ('url', models.URLField(help_text='URL de destination du webhook', max_length=500, verbose_name='URL')),
                ('secret', models.CharField(editable=False, help_text='Secret pour signer les requetes (HMAC-SHA256)', max_length=64, verbose_name='Secret')),
                ('events', models.JSONField(default=list, help_text="Liste des types d'evenements a envoyer", verbose_name='Evenements')),
                ('is_active', models.BooleanField(default=True, help_text='Le webhook est-il actif ?', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('total_deliveries', models.PositiveIntegerField(default=0, verbose_name='Total livraisons')),
                ('successful_deliveries', models.PositiveIntegerField(default=0, verbose_name='Livraisons reussies')),
                ('last_delivery_at', models.DateTimeField(blank=True, null=True, verbose_name='Derniere livraison')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to=settings.AUTH_USER_MODEL, verbose_name='Cree par')),
            ],
            options={
                'verbose_name': 'Webhook',
                'verbose_name_plural': 'Webhooks',
                'db_table': 'webhooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('article.created', 'Article cree'), ('article.updated', 'Article mis a jour'), ('article.deleted', 'Article supprime'), ('article.published', 'Article publie'), ('project.created', 'Projet cree'), ('project.updated', 'Projet mis a jour'), ('project.deleted', 'Projet supprime'), ('experience.created', 'Experience creee'), ('experience.updated', 'Experience mise a jour'), ('experience.deleted', 'Experience supprimee'), ('contact.received', 'Message de contact recu'), ('stack.created', 'Stack cree'), ('stack.updated', 'Stack mis a jour')], max_length=50, verbose_name="Type d'evenement")),
                ('payload', models.JSONField(help_text='Donnees envoyees', verbose_name='Payload')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('success', 'Succes'), ('failed', 'Echec'), ('retrying', 'Nouvelle tentative')], default='pending', max_length=20, verbose_name='Status')),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Code HTTP reponse')),
                ('response_body', models.TextField(blank=True, verbose_name='Corps de la reponse')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Tentatives')),
                ('next_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='Prochaine tentative')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duree (ms)')),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='webhooks.webhook', verbose_name='Webhook')),
            ],
            options={
                'verbose_name': 'Livraison webhook',
                'verbose_name_plural': 'Livraisons webhooks',
                'db_table': 'webhook_deliveries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='webhook_del_status_e36059_idx'), models.Index(fields=['webhook', '-created_at'], name='webhook_del_webhook_b549ed_idx')],
            },
        ),
    ]
