# Generated by Django 5.2.1 on 2026-03-04 15:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookdelivery',
            name='event_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Identifiant unique pour la deduplication', verbose_name='ID evenement'),
        ),
        migrations.AddConstraint(
            model_name='webhookdelivery',
            constraint=models.UniqueConstraint(fields=('webhook', 'event_id'), name='unique_webhook_event_id'),
        ),
    ]
