# Generated by Django 5.2.1 on 2026-03-08 17:11

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0002_webhookdelivery_event_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhook",
            name="url",
            field=models.URLField(
                help_text="URL de destination du webhook",
                max_length=500,
                validators=[utils.validators.validate_webhook_url],
                verbose_name="URL",
            ),
        ),
    ]
