# Generated by Django 5.2.1 on 2026-03-10 22:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0003_alter_webhook_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="webhook",
            index=models.Index(fields=["is_active", "-created_at"], name="webhooks_is_acti_6b7670_idx"),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(fields=["event_type"], name="webhook_del_event_t_d86659_idx"),
        ),
    ]
