# Generated by Django 5.2.1 on 2026-03-02 23:19

import core.user.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='adresse email')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='prenom')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='nom')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='numero telephone')),
                ('bio', models.TextField(blank=True, verbose_name='biographie')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=core.user.models.user_avatar_upload_to)),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='poste')),
                ('public_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email public')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('github', models.URLField(blank=True, null=True, verbose_name='GitHub')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='statut staff')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date inscription')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='derniere mise a jour')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='ResetPasswordCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('code', models.CharField(max_length=8)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'password_reset_codes',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['email', 'code'], name='idx_reset_email_code')],
            },
        ),
    ]
