# Generated by Django 5.2.1 on 2026-03-10 22:58

import core.user.models
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_unique_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.user.models.user_avatar_upload_to,
                validators=[utils.validators.validate_image_upload],
            ),
        ),
    ]
