import {
    Activity,
    AlertCircle,
    AlertTriangle,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    ArrowUpDown,
    Award,
    BarChart2,
    Book,
    BookOpen,
    Briefcase,
    Bug,
    Building2,
    Calendar,
    Camera,
    Check,
    CheckCircle,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    ChevronsLeft,
    ChevronsRight,
    Circle,
    Clock,
    Cloud,
    Code,
    Cpu,
    Database,
    Download,
    Edit,
    ExternalLink,
    Eye,
    EyeOff,
    File,
    FileText,
    FolderKanban,
    FolderOpen,
    GitBranch,
    Github,
    GraduationCap,
    Grid3x3,
    Hash,
    Home,
    Image,
    ImageOff,
    Images,
    Inbox,
    Info,
    Laptop,
    Layers,
    Layout,
    LayoutDashboard,
    LineChart,
    Link,
    Linkedin,
    Loader2,
    Lock,
    LogOut,
    Mail,
    MapPin,
    Menu,
    MessageSquare,
    Minus,
    Monitor,
    Moon,
    Newspaper,
    Palette,
    PanelLeftClose,
    Phone,
    PieChart,
    Plus,
    RefreshCw,
    Reply,
    Save,
    Search,
    SearchX,
    Send,
    Server,
    ServerOff,
    Settings,
    Shield,
    ShieldAlert,
    ShieldOff,
    Smartphone,
    SquareCode,
    Star,
    Sun,
    Trash2,
    TrendingDown,
    TrendingUp,
    Twitter,
    Upload,
    UploadCloud,
    User,
    UserX,
    WifiOff,
    Wrench,
    X,
    XCircle,
    Zap,
    Quote,
    Share2,
} from 'lucide-vue-next';

import type { Component } from 'vue';

export const ICON_REGISTRY: Record<string, Component> = {
    Activity,
    AlertCircle,
    AlertTriangle,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    ArrowUpDown,
    Award,
    BarChart2,
    Book,
    BookOpen,
    Briefcase,
    Bug,
    Building2,
    Calendar,
    Camera,
    Check,
    CheckCircle,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    ChevronsLeft,
    ChevronsRight,
    Circle,
    Clock,
    Cloud,
    Code,
    Cpu,
    Database,
    Download,
    Edit,
    ExternalLink,
    Eye,
    EyeOff,
    File,
    FileText,
    FolderKanban,
    FolderOpen,
    GitBranch,
    Github,
    GraduationCap,
    Grid3x3,
    Hash,
    Home,
    Image,
    ImageOff,
    Images,
    Inbox,
    Info,
    Laptop,
    Layers,
    Layout,
    LayoutDashboard,
    LineChart,
    Link,
    Linkedin,
    Loader2,
    Lock,
    LogOut,
    Mail,
    MapPin,
    Menu,
    MessageSquare,
    Minus,
    Monitor,
    Moon,
    Newspaper,
    Palette,
    PanelLeftClose,
    Phone,
    PieChart,
    Plus,
    RefreshCw,
    Reply,
    Save,
    Search,
    SearchX,
    Send,
    Server,
    ServerOff,
    Settings,
    Shield,
    ShieldAlert,
    ShieldOff,
    Smartphone,
    SquareCode,
    Star,
    Sun,
    Trash2,
    TrendingDown,
    TrendingUp,
    Twitter,
    Upload,
    UploadCloud,
    User,
    UserX,
    WifiOff,
    Wrench,
    Quote,
    Share2,
    X,
    XCircle,
    Zap,
};

// Aliases sémantiques: short name -> clé registry PascalCase
export const ICON_ALIASES: Record<string, string> = {
    close: 'X',
    error: 'XCircle',
    success: 'CheckCircle',
    warning: 'AlertTriangle',
    projects: 'Laptop',
    experience: 'Briefcase',
    stacks: 'Layers',
    blog: 'Newspaper',
    folder: 'FolderOpen',
    refresh: 'RefreshCw',
    message: 'MessageSquare',
    'code-square': 'SquareCode',
    tool: 'Wrench',
    chart: 'BarChart2',
    'chart-line': 'LineChart',
    grid: 'Grid3x3',
    loader: 'Loader2',
    sun: 'Sun',
    moon: 'Moon',
    monitor: 'Monitor',
    'arrow-up-down': 'ArrowUpDown',
    medium: 'BookOpen',
    'panel-left-close': 'PanelLeftClose',
};
