import type { AsyncComponentLoader } from 'vue';

export const ICON_REGISTRY: Record<string, AsyncComponentLoader> = {
    Activity: () => import('lucide-vue-next/dist/esm/icons/activity.js').then((m) => m.default),
    AlertCircle: () => import('lucide-vue-next/dist/esm/icons/circle-alert.js').then((m) => m.default),
    AlertTriangle: () => import('lucide-vue-next/dist/esm/icons/triangle-alert.js').then((m) => m.default),
    ArrowLeft: () => import('lucide-vue-next/dist/esm/icons/arrow-left.js').then((m) => m.default),
    ArrowRight: () => import('lucide-vue-next/dist/esm/icons/arrow-right.js').then((m) => m.default),
    ArrowUp: () => import('lucide-vue-next/dist/esm/icons/arrow-up.js').then((m) => m.default),
    ArrowUpDown: () => import('lucide-vue-next/dist/esm/icons/arrow-up-down.js').then((m) => m.default),
    Award: () => import('lucide-vue-next/dist/esm/icons/award.js').then((m) => m.default),
    BarChart2: () => import('lucide-vue-next/dist/esm/icons/chart-no-axes-column.js').then((m) => m.default),
    Book: () => import('lucide-vue-next/dist/esm/icons/book.js').then((m) => m.default),
    BookOpen: () => import('lucide-vue-next/dist/esm/icons/book-open.js').then((m) => m.default),
    Briefcase: () => import('lucide-vue-next/dist/esm/icons/briefcase.js').then((m) => m.default),
    Bug: () => import('lucide-vue-next/dist/esm/icons/bug.js').then((m) => m.default),
    Building2: () => import('lucide-vue-next/dist/esm/icons/building-2.js').then((m) => m.default),
    Calendar: () => import('lucide-vue-next/dist/esm/icons/calendar.js').then((m) => m.default),
    Camera: () => import('lucide-vue-next/dist/esm/icons/camera.js').then((m) => m.default),
    Check: () => import('lucide-vue-next/dist/esm/icons/check.js').then((m) => m.default),
    CheckCircle: () => import('lucide-vue-next/dist/esm/icons/circle-check-big.js').then((m) => m.default),
    ChevronDown: () => import('lucide-vue-next/dist/esm/icons/chevron-down.js').then((m) => m.default),
    ChevronLeft: () => import('lucide-vue-next/dist/esm/icons/chevron-left.js').then((m) => m.default),
    ChevronRight: () => import('lucide-vue-next/dist/esm/icons/chevron-right.js').then((m) => m.default),
    ChevronUp: () => import('lucide-vue-next/dist/esm/icons/chevron-up.js').then((m) => m.default),
    ChevronsLeft: () => import('lucide-vue-next/dist/esm/icons/chevrons-left.js').then((m) => m.default),
    ChevronsRight: () => import('lucide-vue-next/dist/esm/icons/chevrons-right.js').then((m) => m.default),
    Circle: () => import('lucide-vue-next/dist/esm/icons/circle.js').then((m) => m.default),
    Clock: () => import('lucide-vue-next/dist/esm/icons/clock.js').then((m) => m.default),
    Cloud: () => import('lucide-vue-next/dist/esm/icons/cloud.js').then((m) => m.default),
    Code: () => import('lucide-vue-next/dist/esm/icons/code.js').then((m) => m.default),
    Cpu: () => import('lucide-vue-next/dist/esm/icons/cpu.js').then((m) => m.default),
    Database: () => import('lucide-vue-next/dist/esm/icons/database.js').then((m) => m.default),
    Download: () => import('lucide-vue-next/dist/esm/icons/download.js').then((m) => m.default),
    Edit: () => import('lucide-vue-next/dist/esm/icons/square-pen.js').then((m) => m.default),
    ExternalLink: () => import('lucide-vue-next/dist/esm/icons/external-link.js').then((m) => m.default),
    Eye: () => import('lucide-vue-next/dist/esm/icons/eye.js').then((m) => m.default),
    EyeOff: () => import('lucide-vue-next/dist/esm/icons/eye-off.js').then((m) => m.default),
    File: () => import('lucide-vue-next/dist/esm/icons/file.js').then((m) => m.default),
    FileText: () => import('lucide-vue-next/dist/esm/icons/file-text.js').then((m) => m.default),
    FolderKanban: () => import('lucide-vue-next/dist/esm/icons/folder-kanban.js').then((m) => m.default),
    FolderOpen: () => import('lucide-vue-next/dist/esm/icons/folder-open.js').then((m) => m.default),
    GitBranch: () => import('lucide-vue-next/dist/esm/icons/git-branch.js').then((m) => m.default),
    Github: () => import('lucide-vue-next/dist/esm/icons/github.js').then((m) => m.default),
    GraduationCap: () => import('lucide-vue-next/dist/esm/icons/graduation-cap.js').then((m) => m.default),
    Grid3x3: () => import('lucide-vue-next/dist/esm/icons/grid-3x3.js').then((m) => m.default),
    Hash: () => import('lucide-vue-next/dist/esm/icons/hash.js').then((m) => m.default),
    Home: () => import('lucide-vue-next/dist/esm/icons/house.js').then((m) => m.default),
    Image: () => import('lucide-vue-next/dist/esm/icons/image.js').then((m) => m.default),
    ImageOff: () => import('lucide-vue-next/dist/esm/icons/image-off.js').then((m) => m.default),
    Images: () => import('lucide-vue-next/dist/esm/icons/images.js').then((m) => m.default),
    Inbox: () => import('lucide-vue-next/dist/esm/icons/inbox.js').then((m) => m.default),
    Info: () => import('lucide-vue-next/dist/esm/icons/info.js').then((m) => m.default),
    Laptop: () => import('lucide-vue-next/dist/esm/icons/laptop.js').then((m) => m.default),
    Layers: () => import('lucide-vue-next/dist/esm/icons/layers.js').then((m) => m.default),
    Layout: () => import('lucide-vue-next/dist/esm/icons/panels-top-left.js').then((m) => m.default),
    LayoutDashboard: () => import('lucide-vue-next/dist/esm/icons/layout-dashboard.js').then((m) => m.default),
    LineChart: () => import('lucide-vue-next/dist/esm/icons/chart-line.js').then((m) => m.default),
    Link: () => import('lucide-vue-next/dist/esm/icons/link.js').then((m) => m.default),
    Linkedin: () => import('lucide-vue-next/dist/esm/icons/linkedin.js').then((m) => m.default),
    Loader2: () => import('lucide-vue-next/dist/esm/icons/loader-circle.js').then((m) => m.default),
    Lock: () => import('lucide-vue-next/dist/esm/icons/lock.js').then((m) => m.default),
    LogOut: () => import('lucide-vue-next/dist/esm/icons/log-out.js').then((m) => m.default),
    Mail: () => import('lucide-vue-next/dist/esm/icons/mail.js').then((m) => m.default),
    MapPin: () => import('lucide-vue-next/dist/esm/icons/map-pin.js').then((m) => m.default),
    Menu: () => import('lucide-vue-next/dist/esm/icons/menu.js').then((m) => m.default),
    MessageSquare: () => import('lucide-vue-next/dist/esm/icons/message-square.js').then((m) => m.default),
    Minus: () => import('lucide-vue-next/dist/esm/icons/minus.js').then((m) => m.default),
    Monitor: () => import('lucide-vue-next/dist/esm/icons/monitor.js').then((m) => m.default),
    Moon: () => import('lucide-vue-next/dist/esm/icons/moon.js').then((m) => m.default),
    Newspaper: () => import('lucide-vue-next/dist/esm/icons/newspaper.js').then((m) => m.default),
    Palette: () => import('lucide-vue-next/dist/esm/icons/palette.js').then((m) => m.default),
    PanelLeftClose: () => import('lucide-vue-next/dist/esm/icons/panel-left-close.js').then((m) => m.default),
    Phone: () => import('lucide-vue-next/dist/esm/icons/phone.js').then((m) => m.default),
    PieChart: () => import('lucide-vue-next/dist/esm/icons/chart-pie.js').then((m) => m.default),
    Plus: () => import('lucide-vue-next/dist/esm/icons/plus.js').then((m) => m.default),
    RefreshCw: () => import('lucide-vue-next/dist/esm/icons/refresh-cw.js').then((m) => m.default),
    Reply: () => import('lucide-vue-next/dist/esm/icons/reply.js').then((m) => m.default),
    Save: () => import('lucide-vue-next/dist/esm/icons/save.js').then((m) => m.default),
    Search: () => import('lucide-vue-next/dist/esm/icons/search.js').then((m) => m.default),
    SearchX: () => import('lucide-vue-next/dist/esm/icons/search-x.js').then((m) => m.default),
    Send: () => import('lucide-vue-next/dist/esm/icons/send.js').then((m) => m.default),
    Server: () => import('lucide-vue-next/dist/esm/icons/server.js').then((m) => m.default),
    ServerOff: () => import('lucide-vue-next/dist/esm/icons/server-off.js').then((m) => m.default),
    Settings: () => import('lucide-vue-next/dist/esm/icons/settings.js').then((m) => m.default),
    Shield: () => import('lucide-vue-next/dist/esm/icons/shield.js').then((m) => m.default),
    ShieldAlert: () => import('lucide-vue-next/dist/esm/icons/shield-alert.js').then((m) => m.default),
    ShieldOff: () => import('lucide-vue-next/dist/esm/icons/shield-off.js').then((m) => m.default),
    Smartphone: () => import('lucide-vue-next/dist/esm/icons/smartphone.js').then((m) => m.default),
    SquareCode: () => import('lucide-vue-next/dist/esm/icons/square-code.js').then((m) => m.default),
    Star: () => import('lucide-vue-next/dist/esm/icons/star.js').then((m) => m.default),
    Sun: () => import('lucide-vue-next/dist/esm/icons/sun.js').then((m) => m.default),
    Trash2: () => import('lucide-vue-next/dist/esm/icons/trash-2.js').then((m) => m.default),
    TrendingDown: () => import('lucide-vue-next/dist/esm/icons/trending-down.js').then((m) => m.default),
    TrendingUp: () => import('lucide-vue-next/dist/esm/icons/trending-up.js').then((m) => m.default),
    Twitter: () => import('lucide-vue-next/dist/esm/icons/twitter.js').then((m) => m.default),
    Upload: () => import('lucide-vue-next/dist/esm/icons/upload.js').then((m) => m.default),
    UploadCloud: () => import('lucide-vue-next/dist/esm/icons/cloud-upload.js').then((m) => m.default),
    User: () => import('lucide-vue-next/dist/esm/icons/user.js').then((m) => m.default),
    UserX: () => import('lucide-vue-next/dist/esm/icons/user-x.js').then((m) => m.default),
    WifiOff: () => import('lucide-vue-next/dist/esm/icons/wifi-off.js').then((m) => m.default),
    Wrench: () => import('lucide-vue-next/dist/esm/icons/wrench.js').then((m) => m.default),
    Quote: () => import('lucide-vue-next/dist/esm/icons/quote.js').then((m) => m.default),
    Share2: () => import('lucide-vue-next/dist/esm/icons/share-2.js').then((m) => m.default),
    X: () => import('lucide-vue-next/dist/esm/icons/x.js').then((m) => m.default),
    XCircle: () => import('lucide-vue-next/dist/esm/icons/circle-x.js').then((m) => m.default),
    Zap: () => import('lucide-vue-next/dist/esm/icons/zap.js').then((m) => m.default),
};

// Short aliases -> registry key (PascalCase).
export const ICON_ALIASES: Record<string, string> = {
    close: 'X',
    error: 'XCircle',
    success: 'CheckCircle',
    warning: 'AlertTriangle',
    projects: 'Laptop',
    experience: 'Briefcase',
    stacks: 'Layers',
    blog: 'Newspaper',
    folder: 'FolderOpen',
    refresh: 'RefreshCw',
    message: 'MessageSquare',
    'code-square': 'SquareCode',
    tool: 'Wrench',
    chart: 'BarChart2',
    'chart-line': 'LineChart',
    grid: 'Grid3x3',
    loader: 'Loader2',
    sun: 'Sun',
    moon: 'Moon',
    monitor: 'Monitor',
    'arrow-up-down': 'ArrowUpDown',
    medium: 'BookOpen',
    'panel-left-close': 'PanelLeftClose',
};
