# Generated by Django 5.2.1 on 2026-03-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('medium', models.URLField(blank=True)),
                ('availability_status', models.CharField(choices=[('available', 'Disponible'), ('limited', 'Disponibilite limitee'), ('unavailable', 'Indisponible')], default='available', max_length=20)),
                ('availability_message', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Information de contact',
                'verbose_name_plural': 'Informations de contact',
                'db_table': 'contact_info',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'db_table': 'faq',
                'ordering': ['order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('reference_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('responded', 'Repondu'), ('closed', 'Cloture')], default='new', max_length=20)),
                ('response_message', models.TextField(blank=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'contact',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='contact_status_c674f7_idx'), models.Index(fields=['email'], name='contact_email_7a7031_idx'), models.Index(fields=['reference_id'], name='contact_referen_81a485_idx'), models.Index(fields=['ip_address'], name='contact_ip_addr_02ed66_idx'), models.Index(fields=['created_at'], name='contact_created_c3f495_idx')],
            },
        ),
    ]
