# Generated by Django 5.2.1 on 2026-03-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contact',
            name='contact_status_c674f7_idx',
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['status', '-created_at'], name='contact_status_ec6730_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['is_published', 'order'], name='faq_is_publ_a00273_idx'),
        ),
        migrations.AddConstraint(
            model_name='contactinfo',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('is_primary',), name='unique_primary_contact_info'),
        ),
    ]
