# Generated by Django 5.2.1 on 2026-03-02 23:26

import core.experiences.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': "Type d'experience",
                'verbose_name_plural': "Types d'experiences",
                'db_table': 'experience_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('period', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to=core.experiences.models.experience_logo_upload_to)),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('achievements', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiences', to='experiences.experiencetype')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'db_table': 'experiences',
                'ordering': ['-start_date', 'title'],
                'indexes': [models.Index(fields=['start_date'], name='experiences_start_d_1f1fe3_idx'), models.Index(fields=['type'], name='experiences_type_id_912a46_idx'), models.Index(fields=['end_date'], name='experiences_end_dat_54df2f_idx'), models.Index(fields=['company'], name='experiences_company_ab072a_idx')],
            },
        ),
    ]
