# Generated by Django 5.2.1 on 2026-03-10 22:58

import utils.upload
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.upload.UploadTo(
                    fallback="unknown", prefix="experiences", slug_source=("company", "title")
                ),
                validators=[utils.validators.validate_image_upload],
            ),
        ),
    ]
