# Generated by Django 5.2.1 on 2026-03-02 23:26

import core.articles.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categories',
                'db_table': 'article_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'article_tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('excerpt', models.TextField()),
                ('content', models.JSONField(default=list)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.articles.models.article_image_upload_to)),
                ('read_time', models.PositiveIntegerField(default=5)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='articles.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='articles.tag')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'db_table': 'articles',
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['slug'], name='articles_slug_c8b0c2_idx'), models.Index(fields=['is_published'], name='articles_is_publ_badb53_idx'), models.Index(fields=['published_date'], name='articles_publish_ab562d_idx'), models.Index(fields=['category'], name='articles_categor_11f3b8_idx'), models.Index(fields=['is_published', '-published_date'], name='articles_is_publ_15e299_idx'), models.Index(fields=['category', 'is_published', '-published_date'], name='articles_categor_24564e_idx'), models.Index(fields=['is_featured', 'is_published', '-published_date'], name='articles_is_feat_ffba2e_idx')],
            },
        ),
    ]
