# Generated by Django 5.2.1 on 2026-03-10 22:58

import utils.upload
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_normalize_content_blocks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.upload.UploadTo(fallback="article", prefix="article", slug_source="title"),
                validators=[utils.validators.validate_image_upload],
            ),
        ),
    ]
