# Generated by Django 5.2.1 on 2026-03-02 18:30

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ViewLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "content_type",
                    models.CharField(
                        choices=[("article", "Article"), ("project", "Projet"), ("stack", "Stack")], max_length=20
                    ),
                ),
                ("content_id", models.PositiveIntegerField()),
                ("viewed_at", models.DateField(default=timezone.now)),
                ("count", models.PositiveIntegerField(default=1)),
            ],
            options={
                "verbose_name": "Log de vue",
                "verbose_name_plural": "Logs de vues",
                "db_table": "view_logs",
                "indexes": [
                    models.Index(fields=["viewed_at"], name="view_logs_viewed__5b8ec5_idx"),
                    models.Index(fields=["content_type", "content_id"], name="view_logs_content_c36457_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_type", "content_id", "viewed_at"), name="unique_view_log_per_day"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WebVitalEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "metric_name",
                    models.CharField(
                        choices=[
                            ("LCP", "Largest Contentful Paint"),
                            ("CLS", "Cumulative Layout Shift"),
                            ("INP", "Interaction to Next Paint"),
                            ("FCP", "First Contentful Paint"),
                            ("TTFB", "Time to First Byte"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("value", models.FloatField()),
                (
                    "rating",
                    models.CharField(
                        choices=[("good", "Good"), ("needs-improvement", "Needs Improvement"), ("poor", "Poor")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("delta", models.FloatField(default=0)),
                ("metric_id", models.CharField(db_index=True, max_length=255)),
                ("path", models.CharField(db_index=True, max_length=512)),
                ("full_url", models.TextField(blank=True)),
                ("user_agent", models.TextField(blank=True)),
                ("language", models.CharField(blank=True, max_length=20, null=True)),
                ("viewport_width", models.PositiveIntegerField(blank=True, null=True)),
                ("viewport_height", models.PositiveIntegerField(blank=True, null=True)),
                ("connection_type", models.CharField(blank=True, max_length=64, null=True)),
                ("is_mobile", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Web Vitals Event",
                "verbose_name_plural": "Web Vitals Events",
                "db_table": "web_vital_events",
                "indexes": [
                    models.Index(fields=["metric_name", "created_at"], name="web_vital_e_metric__361ec3_idx"),
                    models.Index(fields=["path", "created_at"], name="web_vital_e_path_7a8f6f_idx"),
                    models.Index(fields=["rating", "created_at"], name="web_vital_e_rating_2293c2_idx"),
                ],
            },
        ),
    ]
