# Generated by Django 5.2.1 on 2026-03-02 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='viewlog',
            new_name='view_logs_viewed__991027_idx',
            old_name='view_logs_viewed__5b8ec5_idx',
        ),
        migrations.RenameIndex(
            model_name='viewlog',
            new_name='view_logs_content_6e2be1_idx',
            old_name='view_logs_content_c36457_idx',
        ),
        migrations.RenameIndex(
            model_name='webvitalevent',
            new_name='web_vital_e_metric__2ffd60_idx',
            old_name='web_vital_e_metric__361ec3_idx',
        ),
        migrations.RenameIndex(
            model_name='webvitalevent',
            new_name='web_vital_e_path_e6a40b_idx',
            old_name='web_vital_e_path_7a8f6f_idx',
        ),
        migrations.RenameIndex(
            model_name='webvitalevent',
            new_name='web_vital_e_rating_eab0c8_idx',
            old_name='web_vital_e_rating_2293c2_idx',
        ),
    ]
